# Generated by Django 4.0 on 2021-12-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
