# Generated by Django 4.0 on 2021-12-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_a', '0002_alter_album_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='libro/'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='pelicula/'),
        ),
    ]
