# Generated by Django 4.0 on 2021-12-29 05:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_a', '0004_alter_libro_portada_alter_pelicula_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
