# Generated by Django 4.0 on 2022-01-11 03:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_a', '0005_album_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
