# Generated by Django 4.0 on 2022-01-13 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_a', '0006_libro_review_pelicula_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='ost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_a.album'),
        ),
    ]
